platform :ios, '9.0'
use_frameworks!

target 'instalexia' do
pod 'RxSwift', '~> 3.0'
pod 'RxCocoa', '~> 3.0'
pod 'RxAlamofire', '~> 3.0'
pod 'Kingfisher', '~> 3.2'
pod 'KeychainSwift', '~> 7.0'
pod 'Alamofire'
end
